//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDdotNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int id { get; set; }
        public string name_product { get; set; }
        public int price { get; set; }
        public int category { get; set; }
        public byte is_delete { get; set; }
    
        public virtual product_category product_category { get; set; }
    }
}
